<?php
//
// File generated by Dolibarr installer 3.8.3 on Jun 27, 2016
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='http://localhost/notebuk_erp';
$dolibarr_main_document_root='C:/xlmpp/htdocs/notebuk_erp';
//$dolibarr_main_url_root_alt='/custom';
//$dolibarr_main_document_root_alt='C:/xlmpp/htdocs/notebuk_erp/custom';
$dolibarr_main_data_root='documents';
$dolibarr_main_db_host='hl230.dinaserver.com';
$dolibarr_main_db_port='';
$dolibarr_main_db_name='erpnote';
$dolibarr_main_db_prefix='sdl_';
$dolibarr_main_db_user='erpnoteb';
$dolibarr_main_db_pass='jjdkd847FF';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='latin1';
$dolibarr_main_db_collation='latin1_swedish_ci';
$dolibarr_main_authentication='dolibarr';

// Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='d365a2239118cb36d78b0f7cbad11207';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
